version: '0.1.0'

services:

  unzip:
    build:
      context: ./01-unzip
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - shared_data:/data

  convert:
    build:
      context: ./02-convert
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - shared_data:/data

  split:
    build:
      context: ./03-split
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    volumes:
      - shared_data:/data

  transform:
    build:
      context: ./04-transform
      dockerfile: Dockerfile
    ports:
      - 8083:8083
    volumes:
      - shared_data:/data

  arango:
    build:
      context: ./05-arango
      dockerfile: Dockerfile
    ports:
      - 8084:8084
    volumes:
      - shared_data:/data

volumes:
  shared_data:
  
